name: Docker Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker-test:
    name: Docker Build Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t portfolio-api:test .

    - name: Test Docker image
      run: |
        # Run container in background
        docker run -d --name test-container -p 8080:8080 portfolio-api:test

        # Wait for container to start
        sleep 10

        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1

        # Test API endpoints
        curl -f http://localhost:8080/api/v1/users || exit 1
        curl -f http://localhost:8080/api/v1/projects || exit 1
        curl -f http://localhost:8080/api/v1/skills || exit 1

        # Stop container
        docker stop test-container
        docker rm test-container

    - name: Login to Docker Hub (on main branch)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to Docker Hub (on main branch)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-api:latest .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-api:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-api:${{ github.sha }}